# Dependencies
markdown:       kramdown
highlighter:    rouge
gems:           [jekyll-paginate]

# Permalinks
permalink:      /blog/:title/

# Setup
title:          jmendeth
tagline:        'blog'
description:    'A personal blog.'
url:            https://jmendeth.com

disqus:
  shortname:    jmendeth

author:
  name:         'Xavier Mendez'
  url:          https://profiles.google.com/114928512048239519236

paginate:       4

# Custom vars
icon:           /assets/images/icon.png
cover:          /assets/images/cover.jpg
theme_color:	C15207

social:
  - icon:       social-twitter
    url:        https://twitter.com/jmendeth
    desc:       Segueix-me a Twitter

  - icon:       social-github
    url:        https://github.com/jmendeth
    desc:       Fork me on Github

  - icon:       social-facebook-alt
    url:        https://facebook.com/jmendeth
    desc:       Follow me on Facebook

  - icon:       feed
    url:        https://jmendeth.com/atom.xml
    desc:       Subscribe to my feed
    
menu:
  - title:      Home
    url:        https://jmendeth.com
    
  - title:      About
    url:        https://jmendeth.com/about


copyright:
  author:       Xavier Mendez
  url:          https://jmendeth.com
  type_title:   Some rights reserved
  type_url:     https://creativecommons.org/licenses/by-nc/3.0
